apiVersion: v1
kind: Service
metadata:
  labels:
    service: credit
  name: credit-service
  namespace: pic
spec:
  selector:
    app: credit
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 80
