version: '0.0.1'

services:
  app:
    image: 'agente:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=cisneros
      - 8080:8080
  db:
    image: 'postgres:11-alpine'
    container_name: DBagenteA
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cisneros